
DROP TABLE IF EXISTS Organisation;
DROP TABLE IF EXISTS Campaign;
DROP TABLE IF EXISTS Sponsor;
DROP TABLE IF EXISTS Volunteer;
DROP TABLE IF EXISTS Mission;
DROP TABLE IF EXISTS Country;
DROP TABLE IF EXISTS AppUser;


CREATE TABLE AppUser (
    ID INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Name VARCHAR(25),
    SurName VARCHAR(25),
    UserName VARCHAR(25) NOT NULL UNIQUE,
    PassWord VARCHAR(50) NOT NULL,
    Role VARCHAR (6) NOT NULL,
    CONSTRAINT CK_User_Role CHECK (Role in ('Admin', 'User'))
);

CREATE TABLE Country (
    ID INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    StateName VARCHAR(25) NOT NULL UNIQUE
);


CREATE TABLE Mission (
     ID INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
     MissionTitle VARCHAR(100) NOT NULL UNIQUE
);


CREATE TABLE Volunteer (
    ID INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Name VARCHAR(20) NOT NULL,
    Surname VARCHAR(25) NOT NULL,
    Specialisation VARCHAR(30) NOT NULL,
    HoursNum int NOT NULL,
    Status VARCHAR(10) NOT NULL,
    CONSTRAINT CK_Volunteer_HoursNum  CHECK (HoursNum > 0),
    CONSTRAINT CK_Volunteer_Status CHECK (Status IN('Active', 'Inactive'))
);


CREATE TABLE Sponsor (
    ID INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Name VARCHAR(20) NOT NULL,
    Surname VARCHAR(25) NOT NULL,
    DonatorType VARCHAR(15),
    CONSTRAINT CK_Sponsor_DonatorType CHECK (DonatorType IN ('Individual', 'Company', 'Foundation'))
);


CREATE TABLE Campaign (
    ID INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    CampaignTitle VARCHAR(50) NOT NULL,
    Budget DECIMAL(9, 2) NOT NULL,
    Deadline VARCHAR(11) NOT NULL,
    CONSTRAINT CK_Campaign_Budget CHECK (Budget > 1000)
);

CREATE TABLE Organisation (
    ID INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Title VARCHAR(50) NOT NULL,
    EstablishmentYear INT NOT NULL,
    NumOfEmployees INT NOT NULL,
    YearlyBudget DECIMAL(12,2) NOT NULL,
    EndGoal VARCHAR(100) NOT NULL,
    Logo VARCHAR(40),

    CountryID int not null,
    MissionID int not null,
    VolunteerID int not null,
    SponsorID int not null,
    CampaignID int not null,

    CONSTRAINT CK_Organisation_Establishment CHECK (EstablishmentYear  >= 1863),
    CONSTRAINT CK_Organisation_NumOfEmployees CHECK (NumOfEmployees > 0),
    CONSTRAINT CK_Organisation_YearlyBudget CHECK (YearlyBudget > 10000),

    CONSTRAINT CK_Org_Country FOREIGN KEY (CountryID) References Country(ID),
    CONSTRAINT CK_Org_Mission FOREIGN KEY (MissionID) References Mission(ID),
    CONSTRAINT CK_Org_Volunteer FOREIGN KEY (VolunteerID) References Volunteer(ID),
    CONSTRAINT CK_Org_Sponsor FOREIGN KEY (SponsorID) References Sponsor(ID),
    CONSTRAINT CK_Org_Campaign FOREIGN KEY (CampaignID) References Campaign(ID)
);

INSERT INTO AppUser (Name, SurName,UserName,PassWord, Role) VALUES
    ('Pino','Banda', 'Admin','Admin', 'Admin'),
    ('Ana','Marija', 'User','User', 'User');

INSERT INTO Country (StateName) VALUES
('United Kingdom'),
('Croatia'),
('United States of America'),
('Germany'),
('Scotland');


INSERT INTO Mission (MissionTitle) VALUES
('Fight against poverty'),
('HealthCare'),
('GreenKeepers'),
('Stop child malnutrition' ),
('Human Rights');

INSERT INTO Volunteer (Name, Surname, Specialisation, HoursNum, Status) VALUES
 ('John', 'Stockton', 'Fundraising', 150, 'Active'),
 ('Mary', 'Middleton', 'Child Education', 500, 'Active'),
 ('Joanna', 'Kensington', 'Promotion', 55, 'Inactive'),
 ('Harry', 'Weasley', 'Medical Doctor', 1200, 'Active');

INSERT INTO Sponsor (Name, Surname, DonatorType) VALUES
('David', 'Packard', 'Foundation'),
('Ben', '& Jerrys', 'Company'),
('Jacob', '& Co.', 'Company'),
('Bill & Melinda', 'Gates', 'Foundation'),
('Ray', 'Dalio', 'Individual');

INSERT INTO Campaign (CampaignTitle, Budget, Deadline) VALUES
('Hot Meals for every Child', 10000, '2026-12-31'),
('Voice for EveryOne <3', 50000, '2026-12-31'),
('Doctor in every house', 80000, '2026-12-31'),
('Every Child deserves a warm Christmas', 90000, '2026-12-31'),
('No one can ban planting a tree', 40000, '2026-12-31'),
('Lets eradicate poverty', 50000, '2026-12-31');

INSERT INTO Organisation (Title, EstablishmentYear, NumOfEmployees, YearlyBudget, EndGoal, Logo, CountryID, MissionID, VolunteerID, SponsorID, CampaignID)
VALUES
    ('The Borgen Project',2003, 200, 607000, 'We fight against child poverty', NULL,3, 1, 1, 4,6 ),
    ('Amnesty International',1961, 3800, 350000000, 'Every human deserves to speak', NULL,1, 5, 3, 1, 2 ),
    ('Marys Meals', 2002, 400, 65000000, 'Every Child deserves a Meal', NULL, 5, 5, 3, 5, 1),
    ('Oxfam', 1942, 5000, 360000000, 'A just world without poverty', NULL, 1, 1, 2, 4, 5),
    ('The Nature Conservancy', 1951, 4000, 1200000000, 'Conserve the lands and waters on which all life depends', NULL, 3, 3, 3, 1, 4)