DELETE FROM Organisation;
DELETE FROM Campaign;
DELETE FROM Sponsor;
DELETE FROM Volunteer;
DELETE FROM Mission;
DELETE FROM Country;

ALTER TABLE Organisation ALTER COLUMN ID RESTART WITH 1;
ALTER TABLE Campaign ALTER COLUMN ID RESTART WITH 1;
ALTER TABLE Sponsor ALTER COLUMN ID RESTART WITH 1;
ALTER TABLE Volunteer ALTER COLUMN ID RESTART WITH 1;
ALTER TABLE Mission ALTER COLUMN ID RESTART WITH 1;
ALTER TABLE Country ALTER COLUMN ID RESTART WITH 1;
